entry:
	mkdir -p bin/
	g++ src/main.cpp -o bin/main -Dshortest -Droundrobin

sjf:
	mkdir -p bin/
	g++ src/main.cpp -o bin/sjf -Dshortest

rr:
	mkdir -p bin/
	g++ src/main.cpp -o bin/rr -Droundrobin

clean:
	rm -rf bin/
	rm *.txt